package com.apms.dto;
import java.io.Serializable;
@SuppressWarnings("serial")
public class AuthorDTO implements Serializable {
    private int authorId;
    private String name;
    private String biography;

    // Default Constructor
    public AuthorDTO() {}

    // Constructor for creating a new Author (ID is generated by DB)
    public AuthorDTO(String name, String biography) {
        this.name = name;
        this.biography = biography;
    }
    
    // Constructor for reading/updating (ID comes from DB)
    public AuthorDTO(int authorId, String name, String biography) {
        this.authorId = authorId;
        this.name = name;
        this.biography = biography;
    }

    // Getters and Setters
    public int getAuthorId() { return authorId; }
    public void setAuthorId(int authorId) { this.authorId = authorId; }
    
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    
    public String getBiography() { return biography; }
    public void setBiography(String biography) { this.biography = biography; }

    @Override
    public String toString() {
        // Useful for UI components like JComboBox
        return name; 
    }
}